---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mssql-secret
  namespace: bitwarden
spec:
  encryptedData:
    mssql-root-password: AgB1LiuC39REeL+5PW4CPEi3JxbwPER593S9+WBcBl9a44tzXqQqxO2P/j1bzz9E8jNGuCBxbXLnJDDyElcB+7QAdvwPN0bo4HSqPhtv88FMI1UrkJ1LtXag5arlF7rmXKmy9oy7SSKUJUqJeOS8MuKzMbir3hFW6aHMB8Hn4rMOcAaJvhrJ/du/vMOXv2DoJ1Ez6MUnDPIN8XaWvNGJtdUoMkU70u9y4mJbPI8RtDOENVO2lHy9se++S3oIuwcmNiOqmOwc8wkN7W3JDpMmbkqh8uka5MPeZqvEZeGVqGNE9PhsiZkTiwUbkyfOgGiTOzSCwKJTHpFuNONc/7sf93WR0+1TamjclhpSicmaS1cfUx804CUW4D0LGI5XIT5UtRlOeIn8AYcLR24Q+sSF/lYLlFDyI7eMrYWtoDJ8M2ENgXHZr3sFxYs5ZYSczCaHUFIEPxRtirfjClPAQLtE8oHNQKJg2TkhR2z7Vw9Fp/ORKaaEVsnJpguYtmzVMJySx/L0bcsujd3U7T/F1g3UrZL2tCLCuQ+juddNbPqd2SczcnKELlGer5BJdSu4K6amVDX7ZG7jNkNsY3fHrapLsYf/R21onVtNCLcCZy1oFEGtMLZKW+uamICgDeXTwENeVmXtgRoXyYbJalxUpc6x0a1C5NSHvOUlDGVgPxZg19Ld7oOoN7bImrwi/bkWoqZcFlWyMyihj9KH/8glhiMAEYjLQphpTgchwHKcUvG+Fj7CZA==
  template:
    metadata:
      creationTimestamp: null
      name: mssql-secret
      namespace: bitwarden
    type: Opaque
