---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-encryption-secret
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgBxRViu2QFXMA7tgrblQJ5CGKV6HRz8yYOzIZrMBLtnrToL9eYWJhXNMbAi1DtLj9cgAiZN0asvLeI9Txw6/3CjVp07mjjlFCaucuHyM28NvVxk3bNNqwNeM+uqC1Cdg3XKCXqIZR/FfYjebRdTpBsJiWD+UIf+q8onhotXGVcfb4GpEjSPpUvCpu1Vlzq2Hdf98FESu2tG/E5U1gC4dVHX1k7W9fA2Tk/2YySMowrXZ0VH2Q3lirCaqzTBkpPeArYoZ5YZ4ZI98GYcJTI9hJHkNtT4QwEMehG9UeUaMy16JOiq977heCjmabRDLlmWcAR9pBSInObZ67vPXMb++HjMAI5LEKGztiGJlWjXLN/zFc3PKFbZJnIg+TFI5e8OQYkgMl9m3Hl1kK5g0EDPkjAi8GIrklOuYPreua1BTZfxje5ADS05OiFPCIc/PjEOfjSCNjutUjecPQOX1/RbCzSupOsMVl13qaXZLvcN8caxbR80S3Iva6y+JGTXW4JjqFH2OQ5FdujQ4v+kCJNHCRto8F2OCuMKnaQRQ/0GmnwJgt3DAWVxnZTh4KT/Hor8qlFPFlpWJ9AzwbEPxuiwVfquVUdP0HX/8B/pJh1nVXn1WV65gxVSKTuwHqOztRTvNSYF0xnoXrc5a2fsKS8FJd/CiAkCYCEIYI0VeTUFnRuCCHq3h6aAy59yd+MrfGT6gAU9d03uy5ADG+D5jTtWuaXSMVCC/dBxqcm0UXtKlDkqQA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-encryption-secret
      namespace: n8n
    type: Opaque
