---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-docstore-secret
  namespace: plane
spec:
  encryptedData:
    aws_access_key: AgC2PpIz3eWousXAjG1o8ch9YWN0U8JiV7PTVYsGukF8dPWX/ozZyrQ2QJLCOFCtcrVuNqzRQBmJsuPTz0xXBBXX+Oq/rFMSaO+AWu4Bm4sNTUCMUoI5BwU6RmNfhtrk9mmcRzRD+aLFb05LIPS8Ac5qomiHHfC8pEyfZfsQ9Uvyqbj7GQm0OuZYsmjNI3SGVaVwDM/9Zr9kFVtcDkAWeIyBwgEjBbcaKXRUG4Xbq8TmFeWnlTzi6qba6OnsHqnxnqoLkq+c8j0lYHifbgFOLaO766iuDjwrS+TiaYLjGeaUzOd2InIFLe+/r1nifjoHkBJleb2SM+KThzC3B+uzR1RdJb6lFmV9P5ZCuigbe3ieWWEUbm64Vk/E8YLyJDt5Y8GvoHuQUfblV92/BaoMUnlBOUoR+vgaL+GDVghJSDK0yJs29lh6K0W21YP7X9B4NGCioCZt6gB1yO7GdvR8Mo2qxQogW/IF73A78iqmv2WnWaOHRh7uFuBp/SYdN7xBHsALTzJKnkRiQ2/dbx50ysMKAkombzvfkON9pZuilffyd9f1tu6+JpEelRVpHkQ2yziJalPF2AaEEGg2Hi16au/PRAUZagTDl/qsmgj2wYlg9owKfZIDjIsr5JtDDU1v+IeJX9BJHoevaSuqTmJP5l+GiRJECZVjtkfcAEjOCB+Smdz5KnyjBppVLBJ3FUZYD6QHJdPLDadBbc4Fgg==
    aws_secret_access_key: AgCv827/smgDuSMw2TDVFS3JdUq0g82ptSzJzoyjx2481HhucVl/eQ1SC6OhDb3XABE9e3TsyIWOdLpphu/qW7axFMNIaFkHP9QqF7N2MxMAqwLSYWP3VMzdRt87v4kYQkWbbUCGAHaLWP8jYVAe7oclpA7SvHE48De/33z1xnQA3oJDdipdMHDTRBHUU/+UYeddMTcUxpFmGCU660NFLL+wRq6jA5ic/Ci/t9x4VG6jTFWpZ9MYcyU45s4K/XaEbaw6VYC6dRUiR+NDmipPgLmWJxP0+IWW5zeWOJ2nJ2gMH973B3nN1LXBAO7uQM2IANIce2F0Y80ovPamU9PMiDKEjOp52xWH8cPBRebz/MQgPyPXK0I86MxPKsqoqaj9K3wZ7/yyNdelswI3R7AMgnRspUxFzxgOdSr8uZbOlllhvmSYMnpCUxO4SepWG8LnXZYS2fLIth3tGhsqleUMqnfsAkEFqazpmFPHHxhGpxAQKU1mnyph/DWq/yxqACdWDEFWnU9aL0ZnB2JHlZP770XLdEFj9q60s5g1ipy7q89RWMRjlvHzE4sitytz7U/9WV+QnaF86w/OgsbZNUtSY69r64ZfaxNyxpClEGELZPsY0pg6b3qRHIN3V3r6r/8Q7/Qod8XHx5UhNuHUhv73UXEaHY23nnE9SUdhGCoxmsHosc9JqI84U3kFPKe33gr67WAiqcA7heZwuqUPxN2Z+5WC+pOEq6i/GSj2Cpq0Hbk/df5FWL0uZzZLXtNC2VhRf6gHsmk3stxtr7VzIWm4hqwm
  template:
    metadata:
      creationTimestamp: null
      name: plane-docstore-secret
      namespace: plane
    type: Opaque
