---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-live-env-secret
  namespace: plane
spec:
  encryptedData:
    live_server_secret_key: AgAoEPZ3gMWzrC8OM25mr0H4KPJ+Xyvzycb4Zu3JHMKzKWYCAiOtaxZwLvN/Z0UqeKANRfWUu7g2lirVlymLVKXQSZeJPNa/JA/r0PMhADormyPdj5fgJ5P2IRnk+qPPTWNeRdOHpQ0k3ejmp0Yw7BqtNHwrIgHMeet9YKHmCtzdHIiyOn8vbrcjL8gQ5Lv8UdyWX0tTiUNohW/exBXJl/C59tMarX03Ky8XQfCyLT4r/5cLlJLaPUl/VtJnS4ZxlZqoHlENE0UtNH8hgUou7OT8GX0Sseif8mbJXGa846o19owwzla8GAXQj2sj2CgKgCP47OhK3unzk1emRxFdRMcRroIZhLf5dLZ12DfmPbFM1EWVRjaPMpIxOBGvNNIc8G29pLQb/wThX5fbMRa36r+aPUPwQoqwUVkrA642L8KP+p+WtWwKe0/MCAUgeIIHw4GeNlow8OWmejiVy9trKb1lxJa6ToKR0XzB2Fomww7Tw2hrd43vB3Yzy+sMLGhh9UTCLCAlvMuL0TtZi5wxDAH0GExvvDTG31sdNiqRwPZXJNXC5ZBJAeI1jcTC37kr9tmkkopircgUQ+WkyM/9Fj2Njuw1bSML863cYh9+z022z+vVyhBgcrotK4c3bl+o6Oe9uHCGHkpGNDQMlX7kKHnggJhZYx/aPczJN/qaTEUlGNHB+F6IPqj+BaxNqgioBUlcQESfvXf1GUC4OOUd6Cjzczy/6MOUtQ2B1i5CiALDxdXKAm0nHcwIFSUTTL+OF1f/bZzxjcMnIRshlhszVHpc
  template:
    metadata:
      creationTimestamp: null
      name: plane-live-env-secret
      namespace: plane
    type: Opaque
