---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-pgdb-secret
  namespace: plane
spec:
  encryptedData:
    password: AgBbgwR9CxEx3x4jfiXnvMDDkmqhoIbP6R6VEgu012slVAPIK0FqidIp7JdCcyooQIkg90st8hjZmXhEfj719Kwzb8G4j43cporXKHZh+x6pRVCpR9BzrL9fy1q9gvIjqXXFJH9ZwfzRQsseobBGROa2OU6FJnpqCmpKqnNgybs1oQJowoOHE0gkSm234wjBuXNMYVirzxy8YNK+ho3KbTcNLm0kBSOp6nWwcC2zFZ+UYJ2d9H3rz4sZA3Dw/Bub5vZnxuXQp9trZZmoxZ5ttrAsD9Au0a8isBHK5H1S+dZnmi2Dbcvr/XLUZjezF2p4Bz3tDZ3dSj382nCW6h8+O7jkaEq2yufOrJmqqZSA/OkdQrfP4rx2JHnRcgWEOvT0fg3KHkzLUq8BhIiNj/h7o2MufmAczUwJb84IUZhjoT00IIQ4cVH+s2ra5bLFlJtQrj5E9v4BkQFasborlw4edXuDJIusHW7wsmDxOEs1vLyMWjjoZeUtHIApKv6V9OUDwGNboootket3qbGImOblwDAGE9trdqrKTex8fY2/xjbCji/ycpPOwsNWAZsHc2fIqGSfC37kSld5QF0t9bYFxx/fMmnRTKFNdR/8MULO5xsmYY4asoDfKcgXOlMwAfgYsxfgxvBrQfRTCfzVXxBE/kIcEQi5Bls1KWH6qzmKBHcd4FoYKYaOXLAHf3BQYZuqg9Z5yTLidzHPJ4NG0J6tIqyyDeHCxEF+oOY2t2sm5guu8Z0bHBzC9eAxBbX6
    username: AgBVgSdbT9Ve0gHMYa5fUZPn4ZQB/JrYG6DKJkFc5LpXgIR98qiU1g81qH5iJkAxq1LfyH9YVCVQkQIHtdz5JUweCETZu0PJPvS/WY7tZNgvOJgp/420V38WLjivnKHsIxlX/tm7gv1Tmjeu7nybr08kHfjvypMHU6BxDMulLrpS53WC0il1hpE1w7V/gDz73cZYLYg5XUQWaz4Jzs2Freeg+oAOXiue+QJz7nXcmLuzSBf6fIi1KPmnoKf1vz7td/CEYoWheMBt5CT5rtqkdins5b8SyRed6iIyc9IMnADuI5ucR9JSQ5Jtc24lZ1VCVcxrhlMMAgTLzr5idg7si8GmVEGm32vV0DmPeWQ88SYuzi0XwW8j57gH+q2uOAgdF6jsv8sEJB3pTcJj4+4gPMB4KGxKFYrx5U1FVnDogSj//MpDKWt3G6X8bFEDFu7io6BAP49VFmJ3aMUQIRDUBSEEtfTWWyGugG86rryr5oVdfjG0osM85yKQ0Y/YhguSvHbXCk7g4a92TK4TRC2yXBy0TXuzwKmFK3oPFhuUlfEbZ9j4oTJXGeVKth5q00m6Ib3Bby4x0NnohN6czVbc7pZFohRBBlb53NM3XgMcIi6mSG3m2vT6PIQHF9psq+KU44Zlvf7usRrR8/g6y5qFWgvaUQCtWApQ/Fk+iyjfO68TyE1FiN1uoqafYvG2BPJ36Vl/kmuOjA==
  template:
    metadata:
      creationTimestamp: null
      name: plane-pgdb-secret
      namespace: plane
    type: Opaque
