---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plane-rabbitmq-secret
  namespace: plane
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgAqBCOoxAMGwLESzAYaCMuj0uLPceXWqq+33G88HjT42yDpUyEfgnFvVvjjaN7HnfiDmpnHv0OO+p1yokle0pKf+UKTc0NxIg6hnu4d/A38StAqgLA2I6mZt36DMLq5HGN1utqfy6LOVq9pHo9ZvAYPR8rETy1egvke/7oOVjUj28ifzT77JWN/wa0TBNWLAuzNWloUEOoSpcghYHmXTM+cpc0JptLcvyHteUgjyFB73vwWTJyXodhkhr0aH2gxFCj+4apozOvDdi+BuzOrilz1nfZr+D+HTo/5hPWa63p/DCDaAX/LxhxxV2LgWIIG30EqhGcO8D9GWsIlBnJjPgSpViPlb/ILX7FZ0aeEaZPmE1bpTkf/46R/fdvE/ghwp4himAqZc5WfTPerY7F+tidCFImDordTuCFrl1pR/magpOVSbbeNNHQ09E3R3hp6V+RtOvdx24AdDYjjxnbt89psKFQsjLo29CpQ/BEH4DSb7XMtX5EZrsZp+rLN2CFZbNil3HZ5AJDkTqC3bTQ6tMrnqRLNImWVeZ9LHlx0C5G4QaEFAnaBPfr9aK77Zi4FLpOHoMKu+8Puqnbnd3WDFTaQiVqiolbr2DNSOAOAzHECPCSGim6+3jksdnadQFUNfKw1a1wZiKdnDWxYjSTbq+sG8pMgeprvynwId2Ff1O9GB7YTZH9gPv5lYzcg6nPy4//Zb92Cm1GRUUSgkyKFOIY/bm/keJiEqIfCguWBUtwWKxHodjCKSS9Z1PNP
    RABBITMQ_DEFAULT_USER: AgB/IwlmEd8oStKbZaFUUVHx3ZNaU0eSV3y93eR9e6q7mR9qq4Ona22u5BDKedaIWFAG+8/SRlcFYvx+87Sbu5u4mdxUug1eVXnMPl/I1U3waqPUoyLHoKPUeBtjSgAdhu22HORNmwlPrylfUTSBpHs8O6UUyT6Sb07hvwXdMTtrN5satH53iBPWeyMOVCpMdxW2OeggjI1P+kXoKsMxCmzqa7qNfSpUgeTdNW2uspst2fX0Hy/cH0pJn1b9Z5sl3kwsSBzdVzBNhGNIYj7sOWUVgnetY2e+nwFuFwVEMvvsdm4Es850UiEYs60ZGyy8TwucFU5KBStqQ0KsIB4jLSLb17Q3Bmcd9SSOxT4H3PZU9wz6KtQaUi1w6mRVPFqgvKEJWnX0DEKiNB+5KPv4qoZr+AfcfB8CBdXrDXNRqNYP51MIkBiGz/YsT26vbh5ZdC/OBLmKGseTgJLZ+s3RqWeb4ln63cbUN8k952CAIuWxPRAw6r5r3WgwTfNaCiAScp4yEPse/lvWxoF+YwUjRO0UaGXl9U5kQXxfd2c86x11bMDrBohGCSyhutuLMgcexdicivPt5HJOPorrTpTtCa3ztj5VA7+xFZlRux6cAir55LP5NdeCXbOQrHpIldQYmSDBxM94PSIZ3Gd2s9sDOVlCTVCYmwfBtC1tf0s0bl6sqb33tSRasWflKXUn7Ta+TbbVbmXxwA==
  template:
    metadata:
      creationTimestamp: null
      name: plane-rabbitmq-secret
      namespace: plane
    type: Opaque
