---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCyGX9ZdIvxX2C6YacXqb39pAR30gmxecedeXaX45WBy6JlITJa8NZTenZyJdEHkAIZliML7DPCtiH3up75jz4YAXiQbjY5DFMPcB789RFIlyGcLpqwsLAnBbUElqsOQtlUlg+Jn6FTYJEcTP5WxmkjimYAOC5bcuLMMQ9E64hbE3HfnAqRox3FXevlpX3wNh6gbIthrN2Webp8qYCYYcp6qXb3YD/BueN4XXaQYJEbDqeliojXH1/uNGrO7Zml6pqpvZ2XmxmtKbFJw+ftI8o8hyww3uwWeGKYRXky70BqzzF16oBkhLwVtdRBfPwBBi2b55KIuB5VNh6pq4Qm/cp81bLcMSyzj51+Tcfrsi3ptwfJJuST9oyE0I8d/4SGBYZA96cjGkG3axczCmedWi2GSgtfcUL4uRha8QE2hHYEe+0Jn+ouj9ekRiXD4XLBkE+TBvfBsJjQ9F0T48UmIkQ6IhbKh/yEGSWw3+GY72gdL6ApmJbuRBVw4T2Ces6cVK4+bZbSbUgDg/OirNsY8Ll8l1vRIXjeqr/qsFdfxJ0rWWzOZKs/LIFvqTbniotq3BE2XKjdz1V7rwMFVFrpc2FHuSmc0Q0vyFuA+HH0j5gHtj8Kpa1DuH3ymmrIkJTvzlmrFUldoKdBGH/Ual4YPfDsx4rvkqL1kU63eowWEgdh3UHdisvqQNxkplurXXKLEmg4l2LZZbiV9gLopRygQN2uqFDB1UoyrwE4rWXUgOAZl6zqxvw4AvzY
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-secret
      namespace: cert-manager
    type: Opaque
