---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: spotizerr-redis-secret
  namespace: media
spec:
  encryptedData:
    redis-password: AgBV4OotzHi1R6SVAqyyTS3AD4E2aMbQsKXslHK5+94xaztqPoQHsNR7TVCpiKP/uH7If/M8UlQ/fqrAsXqFq2hD4oc72DJopCBgAdZLUZ6WD0ZxTS0P2s3eCOIvErK+QYMCPsxS3T7IXUgbSmaSECPHju6rLPgxVJzz4r8fLoN6I0XkIzvKUoo9drG+V/NUGp23tT3BuJD2fpyl5k+PVMuv1VEYC83bMdRmO0m8a0pAjlNyo4tMsVS9BFqfm0wSdGgxdMy/oCL+ZGGBSk8V+RgU449fbfbPuYKFgeSvl2Qduudihait8clTD2xoGXpi5Gxf6hTsOczczY/sJNgrvIRw4fCDZwgZONVaAs/x749rmLuC8yXOY1j8NWxjCxCOLPhuq4lsDBg1cdvWZD8FG04aoc5BI/4eWkzkj8jK4z5ubj/TLRsYUjGt4zYKuAlIBu+rfykiR9t1IalREtSrk43SRUj1qREDdYBdhDQb6M1h51HEu1WyMr/oUf976Rmyaz7ktxbUlFz01qDblLAewfQMjWcFxAHIA8wb+0qp9B3lmgJtEPf/vD/LBegnVulOV8A8adqRaXq6jhdjTH+nU5NBr9InKIDw1c525NHytNo15PDkk7gqARB8DE4HJJtavyBuiaK9Teqzlws4VHboONDcHCm4aEDGGO3On7y304DGyTB/ikO7D0jcxeFjNbPGGcj8ashSg8Kg8b9pHsbx9MMTTVuyH+jXgLfByi6U2Pnr+A==
  template:
    metadata:
      creationTimestamp: null
      name: spotizerr-redis-secret
      namespace: media
    type: Opaque