---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA4qQzH8QBw1tLdJbAuKapWsbVwTg+/kiBJf0VaqH3jMjJgY+JQM+vDH5PK6o0IQomxB2dZkRGK2N6hXDTgilkbcdzJ6qF7gn2+p/gP5WTkkACyXTKV/ejrmbczG9tGZSJL2X1XvrRVFnwbjJ0Y1nhkmHRnHZMZggc86p78Gup9VamOvej5nYby9dRHnEQZi7OU9HavWPJzZyDo84pAgc55xywHDCHfdnygFzjgJ7SQTU1dOlKUDoeUGowFPf9Tzn6IjUDq3mzClpYdDGkc9hSTSByEixRxjxFuk9oWL/ZVZ1yZBK6k16+J0r66C7Xzife5+5foE7QJiZ5zYl6rlcIF4jGJdK2sijF0LIS7vDR0R3UKP8pK+oyv56FG9AitksBQpTYikpexr/UxAjn6ihNX5RZFdkKMDoOj8aB/tAkk6vg9PvhdzFaMPo2NYAT8SaMGuoRKKn8yqQIa0UER5JT2j7jTji5T6Ty7oQwkLGpQePZWq/IxhwKnrAz2/0IxauKzJfjeM4RSYn3zLVdyhdOV37MyAa5qP/t3094Sk7ZKGTCaxqggHQO+Dwn64BE4dfUBqrmgRZYRWj5HyKxhW0zVV9QGF1ynia9H0EpyZAFlFGjb3A9XZGjfrwPuwIOe6wlGKPtHRNG+d98IZSMLSgz7/rJqE+2fk2x6Csrh2bmLHTNaCNtb7ktZQK8dLS8sKQ1Fcdps9p6TmMmbXFM632tHWw==
    client_secret: AgAuiVax2QR1GhEv93TeElrQ21RTHf36bZC9ktC6Ve9J8Q5A5NcspFlRA/v29GIVdqZiMJBQZ3U8P+Wcil+t91BM5v1nChZtS/EUl8h8ZNUp4cM9fRE1P5ijbDXm3IPRnEGXQHMrmkDvo7bzKdtOHeojmG+GZqshjnZklHFqNaJZ9g3cJndd7/rGoWEpgX77iGkc5UyDAWIx66kot2jJTw+cvmsP1tqf2S0VEtAYyBETd9zmjWZdDIIE17FUoyjZEuej3e+zysRNsigYzkBmDjLxgvuOSaIYiU8NP7LSVOFTAxcbGcbJ79MVYAUK0RVHaPyrEjNxngALA72rciF2upy3yBGY/2dnOduTQAvAruceNkirNFBfEfBQ7Wa1CCYDOPgSlJW7YNENq6qd38uZoU5S8z+o4w4xJkLB2fkfwuOguRMlMLyufXnYXrVYtSPCLpJh6Dxcw4dRPEFYSufsgXxb+Hg3rVhDUS8TBGgUxtQoybT/XWOUGTlHVVXfYgf5H126im5f04SbFbji5v8e3KVeXWTnI8gX3OAJWOPkhyn6SXtDu1sl2NjegecjB51KGRfUvO6wRe08gmFeYAu2oEIlGNn0f8zpQOmlZHKePV+mTWCoTaykdz9Zwch2SupcQLLp3t3dhKnJPoGeDD2MwIl1h5pHTpZVtVTlu5LhZda/SuAXFuwgw1jceFn5VeuPBmDZ+tRkJcl1J9CsG/AIK+eoPLNqnk+4aMfqgTXsVuqE9tAi1UVgy96r2XVHvjYWvSDVGzXipxDj3PKi/8eghgE=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
