---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAJ/KcU/RYyCmrwPZG26po/6c+6oitlahoQXHNm3DDpmHBn/nNDubTK9eLN4ipS2uWxw5XS7xzwmn91s8qZzg3+oXLTwgPAupd85zB7qQFKMqxtWr6mTbMWUsjuYt71f2MQQZIDEBdX9Q5lT23tZ7Zr4o2kQqo2ZYsBeGjw61fddDMWUwTpCXJ991vH2bD9Xf90eoxJ7XR7C/489dFW1YFrvp3M44jc2yz8GseBvjbWoNLhiD9zg/CCx6sIVckQ29tALV8Z8UYCEqRDHE90UNpAyx4Z0mpIEi5QoJc2UL01ZPcM5KmkaAkNUIKPfJV7JUsyvZIV6zbJQZeSWbIwn0J69CsOVMOcu4XtYCIZteAHlqPyIg2tJwkqE/7Iqags/YmT5CO+irBD/+kNk2ppQ0k7s3138IlDd+Vb0fnfURFKgiROvf6nq24r2LvTZ2MDIw3h+E/wb7pJBsFCJlpTjktrABrX8GttZ7wEE7Habn3HNH4PwxfzE6iXy1z5HIOb871OpS050r7cxrs+IQuq8GuTMXqqYsOuMEcyRJ2OGdyKZo4jY06UhZLGZj1sjodgoy0pE6t6KZ4PsgApJhhs01FqW29H9N3VVFu+L0wbtnCpijXYhWshklie7kvJusZBFSLGL9INSjPvopvi80Cxl+3/Vw9BtcYOHH3WA1eVEoHJPBa7knT0UImaKVoqG9K4nakzOLT71kl6kT9lJciJgNgTkw==
    client_secret: AgA8F8CcRT0C+BTxgwmITTY8gSlRifwEq2PAIC2ZmuMSL94i2tX+n9ntARTlf3yIfqpP6+R97GX4IU7ekk/fQ1zVoxywbZxOj3ob7p9jHeIsfmCLciu3M2KevmkydUIVb4I+hCkQsRCi1LZFpV1PGleqZVmAGuXBcPsWk7F1X088TP02dWAuV8E9NPHS5eeN+T0SPMk8LnYKleuxN7znO1hRkLsoxUPBzOKtbaCq7VQxm0HQVhTsl9zIPyjMBiKaNy3uFaMZjbB89Kxycfedt6IY8dYQj9dMAFQ7Enbu5tdlEt/QuK4Z1/UARvX7AV1WBJAh3UDL5dx2MBwKjzkdPXBwRmDmpE/xXj00n7sVaFoQ499AuefmMT6LLkX8F1IudTeMCxvHuti/ZiLGmD0Ukt/kG165g4Vl8OLk6tAogM/uRoQWnBnBjidADvlcwewQI1VAokletWfq0PI/pXhRCJmdM3sjTyJ089Y+9wmzCPo6htl1XVt18WBPEMO65slDq9XtVmXaShQNPSgrjal4OnBwDw9TK364CNLtn0w0th2p0kA73tBBoIUDNUfpav1D92mKVrqzfpu6zQGWR2Q6cu8Ai4oHRghHZAa0ZWswg9NozN3SR3T0X4j5Pt+f6Hs5l05nhNyVd31ZB5agDp9n3Vm3ug0lUaz93NzUJJiWG6V8xYF6hFzn/hUhTY+86vZ32utvtKekXttoO5m6shj3VWezgRmL5HdgIO0mMFfShhP2XaKSDqUC2PArTb7kwjb2AryDUmYpMM+lcw95s11eSco=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
