---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCufhR/gQdAq6tOBt1ehe7OkdSC8P9k0/yFMq+9rE4LK5Sp5d/Cv8A5Jh2BKDHYuz8iiwHsJ/7qtbOtb6Kt1XeiJg1NY4aYRd25IGRI1BUVHuSi+z6few2fjPxcllpmSKRaFLSh6+7UtAX9Qf2YCGV5xtN24b1irdd5HaR4yQzk5dU20+E4Y6+HAvEidx0dKhIw/S/Hy54gnbCEDGB9fuIvCE+JRuM5NmRAPffeoRewpliAs87tjd6rQeNNtm4oPiDJzgUzKzjqrZ38P0nPbcIEwK/aAopl0XqnUN/TKZGTUREgvkK1O+IJLCSDE7tyJf5mibFXFr7iz1WTukqwj2XX5Biq0nsSse0sfWBWJNv8Mql+/YzF7HnuU4kdZ0FRCjMXhOLkZ+Cg4azXj+mF8EA8YpZ2kyqZvDpDHZNrebEbxqkMk4vzKiriAOjfBsu+lH5YRw4kf3GXqM39fc512qyGNIsOmTQIN4vU7oMIjer91eOsaA52x7q0wCJz2JKZillFZgw1oYp67v9ml34XvldrYIavktR8+R5kgbkx8IAWQHKH4VHcxP28D0tXAif6EhEV1zZekL6BFbjmz78P31MQOpEoU5K2tT1KOYL6P9TOF8gRxrApf2R9uA7LafGRiJp82yXm404fzCbgBFGX8ixz2JAmhK3L6QDo2/2Gz6wQw+XCxJiCPSH1AwxLmoIy22NcSuU/dj06Q5ID6E/HhlAY4A==
    client_secret: AgBMmu5udYOOm7lS+YiecMBHDP1Lfl3TGvHdw5+jty1vZwCW4YuCz9Sd9lJWbilxthSkdVwJdQR/AeLUq7wHrHexkjMR9v7Cr96wB/hBNJzx9M7/JRHbf/VnuY5I2FYqSe9Pb7Un0PMeSFiyX1gKgweZEAYN2rayjJXpJ/dg41J5t5KE/BN0S+SEBAwEmN4nmq1UxWw4e6SyYU3Q8qn/70cVsbaWGyMfQKsDU//7QKIWC/gcUPOKHUOQ+5CpnGAmthCiGIJsCDxk8fi6Zjjw0IZnAkFR6qJfMUC/WBNQTZqQv8+2KFDg1LGZ1JiGOUFADMLPCv8oPCV4QfRyFVpIeiZ+Hm062AKl0DoGjQyT6iNDOTbUh2Ggc3FGWAR0gVgo99UDXztjnOA/M/K934DRgAfIwcCXFKseUbDqnvnIoIr+L88NVld+H7KTK+Kh0wv3zJnTg5itKUxQZXsGeBQNLP6VC5JUwkLGv1seoPykEtW3wOtT8EqY4YrO1nYEywHVqUoKFjwNlo2Li5+G7g/hMQaNfCXtLgJic6OcVUYzAHZqd0z5hZ87y2Vk78M+Myx45tP0NtNIRT5YR9PDvsIH4L4MLFspvVsEcDZ2jfGoQ6sW/sx+OLb8H7vkovoeeARrOgY1nqiaoEpX/mqGHDRbQ9F13g/wwDhB6AkvfliL29s6HMcbbIt5q46xRUXNGoh5lgaLOfIYRkMn+tkHb9OyD/UPq1O0RTSr2EEpUnzkulleS4S96RCv5kJKKk3odX/a1d3+Dfl5sPPaxOYo5vEyvd8=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
    type: Opaque
