---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-r2-credentials
  namespace: velero
spec:
  encryptedData:
    AWS_ENDPOINTS: AgARlLrOE4DrJ71IM+XjF0CPIGlLdiShjy/bO9/x3a4OMXpB++mHv1VLnFhh/rH0T+6Jj/+fmYomkJotokEQBaX0fJ1e5aMDjBFNSVmItfCKEqPziWhloJYIqKWu6BwdlZ0Yt653+mKuW3jZRok2iHghZT0W2bNkktBAyc8RQLoIaH6PYUuLG/6mlnFhnY7TLb3B0dZKIrDX9GHciWALUzYf1GYDxmY4Q6WJuybkHCB+gmSt+apsSH2lmrjyPrB+2cdkTUs+N5YSMe29f0/cOU7XJ/PP8H/rAYqCTLlezKSzEq7nsRAdL7wLbzTRWACFcB90YvL8JiU0VCgohJgkjsUdZ0xk2oU2CDD84Jm1CktLY7i1c7BzMMpn9DnjEBi9CSUrdmaXFO2mUQTNvTQxVsXgcvFCY3P4bXgujKU2J+EgRqaUpkUa5FWhtE+mcrfYzNMiNjm2VHBT4H/n5c79NT9B+//VNHTBzBXgiZB/cvG3MkTxbiS8y+1KexlI+KdL1E7N0q0stmKLjGi4k9hD7wznpcbfoacO3EBB0/WyDqp2018fE5sW3fEq1rExBZ9JCkAe27cAUhLwKQsRxxn1+n+2BJPdCwhyYZKmgujujVQlN2VZ0dxLnv7wuDeWsRlOlkuE7YTtfGK2lAXbhUaoNQaEJWeco0EuYpEttyEDSEzaSuKSSCxCm8F7AHweosfBVgtwjxQ7UJGJi9plBiM4iRsiWBQsDAa/D0oDgGJNT5XE33mURhGDq9d2zhUsaKjt7y5O+uRX7dF9zrNMu8iDHWT89LjYLg==
    cloud: AgCOIHxH0xcQUsYyxkallxxtV4zHS7JY9k/wziE5sIRrdtEOFgS7docWll9CPZTs8InR1GoPFGFC6G4nH3tgqW2G6IFPxrhjFg/7/UUXyMDJsC6cmlQ741PJcIX6cuiiB0WrsIjVyEqC5Yzl16LUtRVBdjIH1lcEdVlvk2KaRoYO8KisCreMrJvSXHNnDm3UFok2roiwmat7Ldbq/aBCbKgnIjgGd81OfL1OKkIpAe5FSwA6VZx3RGtrWelVZmfJLp0hEkVKFp7mzQLZa/yfWPz5rhpC57vL7IYOZRoKyd34YgTcR2xekb7QlIFnb034f+km7pN7VV80BqJTx4Z1e2VRrx/oqYnxnZ5fcpnHLS1lF+Q9E29+yVC+ZP5hhGMhB7EAh6TX4JAjRsWb/sQ/phy/B1qt2f3LDOTfE0vYTavl5w8scSAYvN6aFPXHyvXIGtO4NKCs7xkrxvNMGv+uygzde3jfuHDDn5m3JiF+ysh78EiZiyViKrcRMpgouXuWFdNw2H9JNnkD8BirYrwP76kka/efkd4SfdjhTSh79k0i76w1pYq0Qb/Oi+MUGPnt89weD7EwcNUgKrdf6PEQf+2fNWWc5UVOoFkRxKcKp6H15RW3NQU4P0T7tlyxvxw6F58Wlh/7aI544iC1ygeAw87/8CNAXkR5nLqFL1Oe97zQGPEV0OucSyULAQOgM03HdwUGGQFzUPPzNlVzX2t5mYSGsz0bF9Rskaptl/ChxOWR15JNOgodfCZyFk6gEQ9GcsX66HM/7XOeDxiLbs6wsprKFRzIB+YBGCPs/adImLz/tGsBOLYCi1UjD0VNWZf/2yoWze+rQM8ETAloomqu4glW9ogy6umhIBCGkvrXLSb4du3juFM1Fx+k2EmVw7kHjovaTyKG
  template:
    metadata:
      creationTimestamp: null
      name: velero-r2-credentials
      namespace: velero
    type: Opaque
